todo:
  container_name: "todo_server"
  env_file: .env.docker
  build: .
  volumes:
    - ".:/src"
  links:
    - "todo_mongo"
    - "todo_redis"
  ports:
    - "3000:3000"

todo_mongo:
  container_name: "todo_mongo"
  image: mongo:3.2.10
  expose:
    - "27017"
  restart: always
  volumes:
    - "/data/db:/data/db"

todo_redis:
  container_name: "todo_redis"
  image: redis:3.2.1
  restart: always
  expose:
    - "6379"